const PublicDocumentsConstants = {
    FETCH_MEETING_DOCS : 'FETCH_MEETING_DOCS',
    FETCH_MEETING_DOCS_SUCCESS : 'FETCH_MEETING_DOCS_SUCCESS',
    FETCH_MEETING_DOCS_FAILURE : 'FETCH_MEETING_DOCS_FAILURE',
    RESET_MEETING_DOCS : 'RESET_MEETING_DOCS',
    FETCH_GROUP_DOCS : 'FETCH_GROUP_DOCS',
    FETCH_GROUP_DOCS_SUCCESS: 'FETCH_GROUP_DOCS_SUCCESS',
    FETCH_GROUP_DOCS_FAILURE: 'FETCH_GROUP_DOCS_FAILURE',
    RESET_GROUP_DOCS : 'RESET_GROUP_DOCS',
    FETCH_GROUP_NOTICES : 'FETCH_GROUP_NOTICES',
    FETCH_GROUP_NOTICES_SUCCESS: 'FETCH_GROUP_NOTICES_SUCCESS',
    FETCH_GROUP_NOTICES_FAILURE: 'FETCH_GROUP_NOTICES_FAILURE',
    FETCH_PUBLIC_DOCS:'FETCH_PUBLIC_DOCS',
    FETCH_PUBLIC_DOCS_SUCCESS:'FETCH_PUBLIC_DOCS_SUCCESS',
    FETCH_PUBLIC_DOCS_FAILURE:'FETCH_PUBLIC_DOCS_FAILURE',
}

const OrganizationalUnitConstants = {
    FETCH_OU_DATA: 'FETCH_OU_DATA',
    FETCH_OU_DATA_SUCCESS: 'FETCH_OU_DATA_SUCCESS',
    FETCH_OU_DATA_FAILURE: 'FETCH_OU_DATA_FAILURE',
}

const FAQConstants = {
    FETCH_FAQ_DATA: 'FETCH_FAQ_DATA',
    FETCH_FAQ_DATA_SUCCESS: 'FETCH_FAQ_DATA_SUCCESS',
    FETCH_FAQ_DATA_FAILURE: 'FETCH_FAQ_DATA_FAILURE',
}

const MainMenuConstants = {
    FETCH_MAIN_MENU_DATA: 'FETCH_MAIN_MENU_DATA',
    FETCH_MAIN_MENU_DATA_SUCCESS: 'FETCH_MAIN_MENU_DATA_SUCCESS',
    FETCH_MAIN_MENU_DATA_FAILURE: 'FETCH_MAIN_MENU_DATA_FAILURE',
}

const PageAsidesConstants = {
    FETCH_PAGE_ASIDES_DATA: 'FETCH_PAGE_ASIDES_DATA',
    FETCH_PAGE_ASIDES_DATA_SUCCESS: 'FETCH_PAGE_ASIDES_DATA_SUCCESS',
    FETCH_PAGE_ASIDES_DATA_FAILURE: 'FETCH_PAGE_ASIDES_DATA_FAILURE',
}
const EB2ServicesConstants = {
    FETCH_DATA: 'FETCH_EB2SERVICES_DATA',
    FETCH_DATA_SUCCESS: 'FETCH_EB2SERVICES_DATA_SUCCESS',
    FETCH_DATA_FAILURE: 'FETCH_EB2SERVICES_DATA_FAILURE',
}
const SystemIndexConstants = {
    FETCH_DATA: 'FETCH_SYSTEMINDEX_DATA',
    FETCH_DATA_SUCCESS: 'FETCH_SYSTEMINDEX_DATA_SUCCESS',
    FETCH_DATA_FAILURE: 'FETCH_SYSTEMINDEX_DATA_FAILURE',
}
const CalendarDataConstants = {
    FETCH_DATA: 'FETCH_CALENDAR_DATA',
    FETCH_DATA_SUCCESS: 'FETCH_CALENDAR_DATA_SUCCESS',
    FETCH_DATA_FAILURE: 'FETCH_CALENDAR_DATA_FAILURE',
}

const SingleNoticeDataConstants = {
    FETCH_DATA: 'FETCH_SINGLE_NOTICE_DATA',
    FETCH_DATA_SUCCESS: 'FETCH_SINGLE_NOTICE_DATA_SUCCESS',
    FETCH_DATA_FAILURE: 'FETCH_SINGLE_NOTICE_DATA_FAILURE',
}

const AlertRequestsDataConstants = {
    PUSH_DATA: 'PUSH_ALERT_REQUEST_DATA',
    PUSH_DATA_SUCCESS: 'PUSH_ALERT_REQUEST_DATA_SUCCESS',
    PUSH_DATA_FAILURE: 'PUSH_ALERT_REQUEST_DATA_FAILURE',
}
const AuthenticationConstants = {
    PUSH_DATA: 'AUTHENTICATION_REQUEST_DATA',
    PUSH_DATA_SUCCESS: 'AUTHENTICATION_REQUEST_DATA_SUCCESS',
    PUSH_DATA_FAILURE: 'AUTHENTICATION_REQUEST_DATA_FAILURE',
}
const SubmitChangeConstants = {
    PUSH_DATA: 'SUBMIT_CHANGE_REQUEST_DATA',
    PUSH_DATA_SUCCESS: 'SUBMIT_CHANGE_REQUEST_DATA_SUCCESS',
    PUSH_DATA_FAILURE: 'SUBMIT_CHANGE_REQUEST_DATA_FAILURE',
}

const NewsRequestsConstants = {
    FETCH_LIST_DATA: 'FETCH_NEWS_LIST_DATA',
    FETCH_LIST_DATA_SUCCESS: 'FETCH_NEWS_LIST_DATA_SUCCESS',
    FETCH_LIST_DATA_FAILURE: 'FETCH_NEWS_LIST_DATA_FAILURE',
    FETCH_DATA_DETAILS: 'FETCH_NEWS_DETAILS_DATA',
    FETCH_DATA_DETAILS_SUCCESS: 'FETCH_NEWS_DETAILS_DATA_SUCCESS',
    FETCH_DATA_DETAILS_FAILURE: 'FETCH_NEWS_DETAILS_DATA_FAILURE',
}



module.exports = {
    PublicDocumentsConstants,
    OrganizationalUnitConstants,
    FAQConstants,
    MainMenuConstants,
    PageAsidesConstants,
    EB2ServicesConstants,
    SystemIndexConstants,
    CalendarDataConstants,
    SingleNoticeDataConstants,
    AlertRequestsDataConstants,
    AuthenticationConstants,
    SubmitChangeConstants,
    NewsRequestsConstants,
}
